abstract: Library containing over 100 Zen Koans.
author: Luke Closs <lukec@cpan.org>
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
name: Zen-Koans
no_index:
  directory:
    - inc
    - t
version: 0.01
